### ISSUE TITLE
orthrus create failed for libpcap

### ISSUE THREAD

**Issue by thelumberjhack** [test-pipeline/orthrus#1]
Hi
I followed your tutorial to setup orthrus with success but when I wanna create the binaries for my libpcap fuzz session I get the following stacktrace:

``` python
~/workspace/fuzzing/pcap/libpcap   master  orthrus create -fuzz -asan -cov
Orthrus 1.01 by Markus Leutner, and Bhargava Shastry <https://github.com/test-pipeline/orthrus> 

[+] Create Orthrus workspace
    [+] Installing binaries for afl-fuzz with AddressSanitizer
        [+] Configure... done
        [+] Compile and install... done
Traceback (most recent call last):
  File "/home/afl/.virtualenvs/afl/bin/orthrus", line 4, in <module>
    __import__('pkg_resources').run_script('orthrus===0.1.-pre-alpha-', 'orthrus')
  File "/home/afl/.virtualenvs/afl/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/afl/.virtualenvs/afl/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1531, in run_script
    exec(code, namespace, namespace)
  File "/home/afl/.virtualenvs/afl/lib/python2.7/site-packages/orthrus-0.1._pre_alpha_-py2.7.egg/EGG-INFO/scripts/orthrus", line 67, in <module>
    tool.run()
  File "/home/afl/.virtualenvs/afl/lib/python2.7/site-packages/orthrus-0.1._pre_alpha_-py2.7.egg/EGG-INFO/scripts/orthrus", line 63, in run
    return self._args.func(self._args)
  File "/home/afl/.virtualenvs/afl/lib/python2.7/site-packages/orthrus-0.1._pre_alpha_-py2.7.egg/EGG-INFO/scripts/orthrus", line 22, in _create
    cmd.run()
  File "/home/afl/.virtualenvs/afl/local/lib/python2.7/site-packages/orthrus-0.1._pre_alpha_-py2.7.egg/orthrus/commands.py", line 127, in run
    if not self.create(install_path, b.BuildEnv.BEnv_afl_asan, 'afl-asan_inst.log'):
  File "/home/afl/.virtualenvs/afl/local/lib/python2.7/site-packages/orthrus-0.1._pre_alpha_-py2.7.egg/orthrus/commands.py", line 95, in create
    sample_binpath = random.choice(util.return_elf_binaries(install_path + 'bin/'))
  File "/usr/lib/python2.7/random.py", line 275, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
```

Any idea on what I am doing wrong?

My setup is a debian jessie box up-to-date, running orthrus and afl-utils in a virtualenv.

Thanks

PS: here is the afl-asan_inst.log where I cannot find anything wrong:

``` bash
rm -f pcap-linux.o pcap-usb-linux.o pcap-bt-linux.o pcap-bt-monitor-linux.o pcap-netfilter-linux.o pcap-dbus.o fad-getad.o pcap.o inet.o fad-helpers.o gencode.o optimize.o nametoaddr.o etherent.o savefile.o sf-pcap.o sf-pcap-ng.o pcap-common.o bpf_image.o bpf_dump.o  scanner.o grammar.o bpf_filter.o version.o  libpcap.* valgrindtest capturetest can_set_rfmon_test filtertest findalldevstest opentest selpolltest libpcap-`cat ./VERSION`.tar.gz scanner.c grammar.c bpf_filter.c version.c scanner.h grammar.h pcap_version.h lex.yy.c pcap-config
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./pcap-linux.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./pcap-usb-linux.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./pcap-bt-linux.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./pcap-bt-monitor-linux.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./pcap-netfilter-linux.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./pcap-dbus.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./fad-getad.c
bison -y -p pcap_ -o grammar.c -d grammar.y
./gen_version_header.sh ./VERSION ./pcap_version.h.in pcap_version.h
flex -P pcap_ --header-file=scanner.h --nounput -o scanner.c scanner.l
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./inet.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./fad-helpers.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./nametoaddr.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./etherent.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./savefile.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./sf-pcap.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./sf-pcap-ng.c
rm -f bpf_filter.c
#
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./bpf_image.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./bpf_dump.c
ln -s ./bpf/net/bpf_filter.c bpf_filter.c
./config.status --file=pcap-config.tmp:./pcap-config.in
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c bpf_filter.c
# Older programs import this if they want to show the
# libpcap version number, rather than calling
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./pcap-common.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./optimize.c
grammar.y: warning: 38 shift/reduce conflicts [-Wconflicts-sr]
# pcap_lib_version(), so we need to export it.
#
./gen_version_c.sh ./VERSION version.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./pcap.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c version.c
config.status: creating pcap-config.tmp
mv pcap-config.tmp pcap-config
chmod a+x pcap-config
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c grammar.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c ./gencode.c
afl-clang -fvisibility=hidden -fpic -O3 -I.  -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -O3    -c scanner.c
VER=`cat ./VERSION`; \
MAJOR_VER=`sed 's/\([0-9][0-9]*\)\..*/\1/' ./VERSION`; \
afl-clang -shared -Wl,-soname,libpcap.so.$MAJOR_VER  \
    -o libpcap.so.$VER pcap-linux.o pcap-usb-linux.o pcap-bt-linux.o pcap-bt-monitor-linux.o pcap-netfilter-linux.o pcap-dbus.o fad-getad.o pcap.o inet.o fad-helpers.o gencode.o optimize.o nametoaddr.o etherent.o savefile.o sf-pcap.o sf-pcap-ng.o pcap-common.o bpf_image.o bpf_dump.o  scanner.o grammar.o bpf_filter.o version.o   -ldbus-1 
ar rc libpcap.a pcap-linux.o pcap-usb-linux.o pcap-bt-linux.o pcap-bt-monitor-linux.o pcap-netfilter-linux.o pcap-dbus.o fad-getad.o pcap.o inet.o fad-helpers.o gencode.o optimize.o nametoaddr.o etherent.o savefile.o sf-pcap.o sf-pcap-ng.o pcap-common.o bpf_image.o bpf_dump.o  scanner.o grammar.o bpf_filter.o version.o  
ranlib libpcap.a
#
# Most platforms have separate suffixes for shared and
# archive libraries, so we install both.
#
[ -d /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/lib ] || \
    (mkdir -p /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/lib; chmod 755 /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/lib)
/usr/bin/install -c -m 644 libpcap.a /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/lib/libpcap.a
ranlib /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/lib/libpcap.a
[ -d /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/lib ] || \
    (mkdir -p /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/lib; chmod 755 /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/lib)
VER=`cat ./VERSION`; \
MAJOR_VER=`sed 's/\([0-9][0-9]*\)\..*/\1/' ./VERSION`; \
/usr/bin/install -c libpcap.so.$VER /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/lib/libpcap.so.$VER; \
ln -sf libpcap.so.$VER /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/lib/libpcap.so.$MAJOR_VER; \
ln -sf libpcap.so.$MAJOR_VER /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/lib/libpcap.so
[ -d /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/lib ] || \
    (mkdir -p /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/lib; chmod 755 /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/lib)
[ -d /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/include ] || \
    (mkdir -p /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/include; chmod 755 /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/include)
[ -d /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/include/pcap ] || \
    (mkdir -p /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/include/pcap; chmod 755 /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/include/pcap)
[ -d /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man1 ] || \
    (mkdir -p /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man1; chmod 755 /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man1)
[ -d /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man3 ] || \
    (mkdir -p /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man3; chmod 755 /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man3)
[ -d /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man5 ] || \
    (mkdir -p /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man5; chmod 755 /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man5)
[ -d /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man7 ] || \
    (mkdir -p /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man7; chmod 755 /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man7)
for i in pcap.h pcap-bpf.h pcap-namedb.h pcap/bpf.h pcap/bluetooth.h pcap/can_socketcan.h pcap/dlt.h pcap/export-defs.h pcap/ipnet.h pcap/namedb.h pcap/nflog.h pcap/pcap.h pcap/sll.h pcap/vlan.h pcap/usb.h; do \
    /usr/bin/install -c -m 644 ./$i \
        /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/include/$i; done
[ -d /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/bin ] || \
    (mkdir -p /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/bin; chmod 755 /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/bin)
/usr/bin/install -c pcap-config /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/bin/pcap-config
for i in pcap-config.1; do \
    /usr/bin/install -c -m 644 ./$i \
        /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man1/$i; done
for i in pcap_activate.3pcap pcap_breakloop.3pcap pcap_can_set_rfmon.3pcap pcap_close.3pcap pcap_create.3pcap pcap_datalink_name_to_val.3pcap pcap_datalink_val_to_name.3pcap pcap_dump.3pcap pcap_dump_close.3pcap pcap_dump_file.3pcap pcap_dump_flush.3pcap pcap_dump_ftell.3pcap pcap_file.3pcap pcap_fileno.3pcap pcap_findalldevs.3pcap pcap_freecode.3pcap pcap_get_selectable_fd.3pcap pcap_geterr.3pcap pcap_inject.3pcap pcap_is_swapped.3pcap pcap_lib_version.3pcap pcap_lookupdev.3pcap pcap_lookupnet.3pcap pcap_loop.3pcap pcap_major_version.3pcap pcap_next_ex.3pcap pcap_offline_filter.3pcap pcap_open_live.3pcap pcap_set_buffer_size.3pcap pcap_set_datalink.3pcap pcap_set_immediate_mode.3pcap pcap_set_promisc.3pcap pcap_set_rfmon.3pcap pcap_set_snaplen.3pcap pcap_set_timeout.3pcap pcap_setdirection.3pcap pcap_setfilter.3pcap pcap_setnonblock.3pcap pcap_snapshot.3pcap pcap_stats.3pcap pcap_statustostr.3pcap pcap_strerror.3pcap pcap_tstamp_type_name_to_val.3pcap pcap_tstamp_type_val_to_name.3pcap; do \
    /usr/bin/install -c -m 644 ./$i \
        /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man3/$i; done
for i in pcap.3pcap pcap_compile.3pcap pcap_datalink.3pcap pcap_dump_open.3pcap pcap_get_tstamp_precision.3pcap pcap_list_datalinks.3pcap pcap_list_tstamp_types.3pcap pcap_open_dead.3pcap pcap_open_offline.3pcap pcap_set_tstamp_precision.3pcap pcap_set_tstamp_type.3pcap; do \
    /usr/bin/install -c -m 644 $i \
        /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man3/$i; done
(cd /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man3 && \
rm -f pcap_datalink_val_to_description.3pcap && \
ln -s pcap_datalink_val_to_name.3pcap \
     pcap_datalink_val_to_description.3pcap && \
rm -f pcap_dump_fopen.3pcap && \
ln -s pcap_dump_open.3pcap pcap_dump_fopen.3pcap && \
rm -f pcap_freealldevs.3pcap && \
ln -s pcap_findalldevs.3pcap pcap_freealldevs.3pcap && \
rm -f pcap_perror.3pcap && \
ln -s pcap_geterr.3pcap pcap_perror.3pcap && \
rm -f pcap_sendpacket.3pcap && \
ln -s pcap_inject.3pcap pcap_sendpacket.3pcap && \
rm -f pcap_free_datalinks.3pcap && \
ln -s pcap_list_datalinks.3pcap pcap_free_datalinks.3pcap && \
rm -f pcap_free_tstamp_types.3pcap && \
ln -s pcap_list_tstamp_types.3pcap pcap_free_tstamp_types.3pcap && \
rm -f pcap_dispatch.3pcap && \
ln -s pcap_loop.3pcap pcap_dispatch.3pcap && \
rm -f pcap_minor_version.3pcap && \
ln -s pcap_major_version.3pcap pcap_minor_version.3pcap && \
rm -f pcap_next.3pcap && \
ln -s pcap_next_ex.3pcap pcap_next.3pcap && \
rm -f pcap_open_dead_with_tstamp_precision.3pcap && \
ln -s pcap_open_dead.3pcap \
     pcap_open_dead_with_tstamp_precision.3pcap && \
rm -f pcap_open_offline_with_tstamp_precision.3pcap && \
ln -s pcap_open_offline.3pcap pcap_open_offline_with_tstamp_precision.3pcap && \
rm -f pcap_fopen_offline.3pcap && \
ln -s pcap_open_offline.3pcap pcap_fopen_offline.3pcap && \
rm -f pcap_fopen_offline_with_tstamp_precision.3pcap && \
ln -s pcap_open_offline.3pcap pcap_fopen_offline_with_tstamp_precision.3pcap && \
rm -f pcap_tstamp_type_val_to_description.3pcap && \
ln -s pcap_tstamp_type_val_to_name.3pcap pcap_tstamp_type_val_to_description.3pcap && \
rm -f pcap_getnonblock.3pcap && \
ln -s pcap_setnonblock.3pcap pcap_getnonblock.3pcap)
for i in pcap-savefile.manfile.in; do \
    /usr/bin/install -c -m 644 `echo $i | sed 's/.manfile.in/.manfile/'` \
        /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man5/`echo $i | sed 's/.manfile.in/.5/'`; done
for i in pcap-filter.manmisc.in pcap-linktype.manmisc.in pcap-tstamp.manmisc.in; do \
    /usr/bin/install -c -m 644 `echo $i | sed 's/.manmisc.in/.manmisc/'` \
        /home/afl/workspace/fuzzing/pcap/libpcap/.orthrus/binaries/afl-asan/share/man/man7/`echo $i | sed 's/.manmisc.in/.7/'`; done

```

**Comment by bshastry** [comment]
Hi @yformaggio Thanks for reporting the issue. It seems like `make install` for `libpcap` does not actually build an ELF binary (that you can fuzz). The attached logs tell me that Orthrus is bailing out (uncleanly) due to this. Can you report to me what the output of these commands are:

``` bash
$ cd ~/workspace/fuzzing/pcap/libpcap && find . -type f -executable -exec file -i {} \; | grep 'x-executable; charset=binary' | cut -d':' -f1
$ find .orthrus/binaries -type f -executable -exec file -i {} \; | grep 'x-executable; charset=binary' | cut -d':' -f1
```

I expect them to be null if my reasoning is correct.

**Comment by thelumberjhack** [comment]
Hi @bshastry, no problem. Thanks for the reply.
Yes you're right it is a library but I need to instrument it for my `tcpdump` fuzzing (for which Orthrus cannot build an Harden binary).

```
find . -type f -executable -exec file -i {} \; | grep 'x-executable; charset=binary' | cut -d':' -f1
```

returns nothing as well as

```
find .orthrus/binaries -type f -executable -exec file -i {} \; | grep 'x-executable; charset=binary' | cut -d':' -f1
```

I tried your fix in the dev branch, now it does not crash with a stack trace:

``` python
orthrus create -fuzz -asan -cov
Orthrus 1.01+dev by Markus Leutner, and Bhargava Shastry <https://github.com/test-pipeline/orthrus> 

[+] Create Orthrus workspace
    [+] Installing binaries for afl-fuzz with AddressSanitizer
        [+] Configuring... done
        [+] Compiling... done
        [+] Looking for ELF binaries... failed. Looks like make install did not build any ELF binaries that we can fuzz
```

Any  chance that Orthrus gonna support libraries in a next future or should I just build the library with afl-clang-fast and use Orthrus only on the binary?

**Comment by bshastry** [comment]
>  but I need to instrument it for my tcpdump fuzzing (for which Orthrus cannot build an Harden binary)

Can you tell me more about why Orthrus cannot build a harden binary for tcpdump?

> Any chance that Orthrus gonna support libraries in a next future or should I just build the library with afl-clang-fast and use Orthrus only on the binary?

I will push a fix for this use case so you can continue the library creation process in spite of no ELF binaries built during install. The caveat is that this skips the instrumentation verification step that is currently supported only for binaries. Having said that, lack of verification may not be a deal breaker. Nonetheless, let me know if libpcap in the respective dirs (Asan, harden etc.) are missing asan/afl specific symbols. You can check them, like so

```
# For asan: Should return a bunch of asan symbols baked into libpcap
$ objdump -t `PATH_TO_ASAN_LIBPCAP` | grep asan
# For afl: likewise for AFL
$ objdump -t `PATH_TO_ASAN_LIBPCAP` | grep afl
```

**Comment by thelumberjhack** [comment]
> Can you tell me more about why Orthrus cannot build a harden binary for tcpdump?

Should I open a new issue for that matter?

> I will push a fix for this use case so you can continue the library creation process in spite of no ELF binaries built during install.

Awesome thanks :)

> Nonetheless, let me know if libpcap in the respective dirs (Asan, harden etc.) are missing asan/afl specific symbols.

Will do as soon as I can access my fuzz box again.

**Comment by bshastry** [comment]
> Should I open a new issue for that matter?

Please do. Also, if you are satisfied with this fix, give me a short ack so I can close this issue.

**Comment by thelumberjhack** [comment]
I tried your fix, and it goes through all the steps for `libpcap`:

``` bash
$ orthrus create -fuzz -asan -cov
Orthrus 1.01+dev by Markus Leutner, and Bhargava Shastry <https://github.com/test-pipeline/orthrus> 

[+] Create Orthrus workspace
    [+] Installing binaries for afl-fuzz with AddressSanitizer
        [+] Configuring... done
        [+] Compiling... done
        [+] Looking for ELF binaries... Could not find ELF binaries. While we cannot guarantee that all libraries were instrumented correctly, they most likely were.
    [+] Installing binaries for debug with AddressSanitizer
        [+] Configuring... done
        [+] Compiling... done
        [+] Looking for ELF binaries... Could not find ELF binaries. While we cannot guarantee that all libraries were instrumented correctly, they most likely were.
    [+] Installing binaries for afl-fuzz in harden mode
        [+] Configuring... done
        [+] Compiling... done
        [+] Looking for ELF binaries... Could not find ELF binaries. While we cannot guarantee that all libraries were instrumented correctly, they most likely were.
    [+] Installing binaries for debug in harden mode
        [+] Configuring... done
        [+] Compiling... done
        [+] Looking for ELF binaries... Could not find ELF binaries. While we cannot guarantee that all libraries were instrumented correctly, they most likely were.
    [+] Installing binaries for obtaining test coverage information
        [+] Configuring... done
        [+] Compiling... done
        [+] Looking for ELF binaries... Could not find ELF binaries. While we cannot guarantee that all libraries were instrumented correctly, they most likely were.
```

Concerning the symbols:

``` bash
$ objdump -t .orthrus/binaries/afl-asan/lib/libpcap.a | grep asan
In archive .orthrus/binaries/afl-asan/lib/libpcap.a:
0000000000028440 l     F .text  0000000000000056 asan.module_ctor
00000000000284a0 l     F .text  000000000000004c asan.module_dtor
[...]

$ objdump -t .orthrus/binaries/afl-asan/lib/libpcap.a | grep afl
In archive .orthrus/binaries/afl-asan/lib/libpcap.a:
00000000000284f0 l       .text  0000000000000000 __afl_maybe_log
0000000000000000 l     O .bss   0000000000000008 __afl_area_ptr
0000000000028520 l       .text  0000000000000000 __afl_setup
[...]
```

You can close the issue now, thanks for the quick fix :+1:

**Comment by bshastry** [comment]
Thanks @yformaggio for reporting the issue. Closing it.
